[package]
name = "Mandelbrot"
version = "0.1.0"
authors = ["Tuan Anh Le <anh.le@myob.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
image = "0.13.0"
crossbeam = "0.8"
